# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k_ota_schema_registry/foo/student.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("k_ota_schema_registry/foo/student.proto", :syntax => :proto3) do
    add_message "k_ota_schema_registry.foo.Student" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
  end
end

module KOtaSchemaRegistry
  module Foo
    Student = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("k_ota_schema_registry.foo.Student").msgclass
  end
end
