# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: k_ota_schema_registry/teacher.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("k_ota_schema_registry/teacher.proto", :syntax => :proto3) do
    add_message "k_ota_schema_registry.Teacher" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
  end
end

module KOtaSchemaRegistry
  Teacher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("k_ota_schema_registry.Teacher").msgclass
end
